[package]
name = "first"
version = "0.1.0"
authors = ["Noah Gleason <noah.gleason1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.3"
serde = { version = "1.0", features = ["derive"] }